---
title: "R Notebook"
author: 'Yudan Zhang'
output: html_notebook
---
# Project1 Introduction: 
 sentiment analysis 
 
```{r}
df = read.csv('/Users/sherry/Documents/Github/fall2022-project1-YudanZhang/data/philosophy_data.csv')
head(df)
```
# EDA 
```{r warning=FALSE}
sprintf('the number of rows: %d', dim(df)[1])
sprintf('the number of columns: %d', dim(df)[2])
# check missing values & nan
is.null(df)
colSums(is.na(df))
```

```{r warning=FALSE}
#### summary of distinct values for each variables ----
library(dplyr)
df %>% 
  summarise_each(funs(n_distinct))

df_noticed <- df[,c('title','author','school','original_publication_date','corpus_edition_date')]
# apply(): 1: rows & 2: columns
df_noticed_summary <- apply(df_noticed, MARGIN = 2, FUN = table) 
df_noticed_summary
# density plot for distinct values
library(ggplot2)
plot1 <- ggplot(df_noticed_summary$title,
                aes(x = )) +    # Draw histogram & density
  geom_histogram(aes(y = ..density..)) + 
  geom_density(col = "#1b98e0", size = 2) + 
  facet_wrap(~ name, scales = "free")
ggp3
```

